#!/bin/bash

# adds additional digital inputs and relay outputs to the Raspberry Pi platforms

# the stock RPI Venus distribution includes two relays and two digital inputs
# adding the additional GPIO pins to /etc/venus/gpio_list
# makes additional digital inputs available
# all 5 defined digital inputs are activated by this script
#
# the Raspberry PI default is for the first 8 GPIO pins to have pull UPs
# and the remaining have pull DOWNs. This makes some digital input pins behave differently
# this script also installs a DT overlay that switches to pull UPs for all digital input pins
#
# Only the first relay can be assigned to a function: alarm, genertor start/stop or pump.
# Others are only provided manual on/off control from the menu.
# Six relays are supported. Only the first relay can be assigned to functions
# The remaining relays are manual on/off only.

# run manually initally, then called from reinstallMods
# to uninstall/deactivate, call this script with "uninstall" as first parameter

# original assignments for relays 5 and 6 create conflicts with interrypt pins
# on hat boards such as the Waveshare dual CANbus hats (regular and FD versions)
# An option in this setup script allows selection of different GPIO assignments
# for relays 5 and 6 to avoid these conflicts
#
# Because this conflict will be rare, the option is considered optional.
# That is, an automatic install WILL be permitted even if a manual install has not
#   been perfomred.
#
# VeCanSetup will alert the user of conflicts and prevent installing the second
#   CANbus interface until this script is rerun to move the relay assignments.

# This package makes the following modifications:
#   - modifies the GPIOs for digital inputs and relay output (relay_1 GPIO 21 -> 16)
#     - relay_1          Pin 40 / GPIO 21 -> Pin 36 / GPIO 16
#     - digital_input_4  Pin 35 / GPIO 19 -> Pin 26 / GPIO  7
#     - digital_input_6  (shutdown pin)      Pin 36 / GPIO 16
#   - installs the overlay file for the SC16IS752 controller (RS485)
#   - installs the udev rules to use the RS485 ports in Venus OS
#   - activates the overlays in config.txt
  
# Note, this script DOES require a system reboot.

gpioListFile="/etc/venus/gpio_list"
rulesFile="/etc/udev/rules.d/wscanrs485.rules"
overlayFile="/u-boot/overlays/sc16is752-spi1.dtbo"
configFile="/u-boot/config.txt"

standardPromptAndActions='yes'

#### following lines incorporate SetupHelper utilities into this script
# Refer to the SetupHelper ReadMe file for details.
    
source "/data/SetupHelper/HelperResources/IncludeHelpers"

#### end of lines to include SetupHelper

#### installing
if [ $scriptAction == 'INSTALL' ] ; then
  updateActiveFile "$gpioListFile"    
  updateActiveFile "$rulesFile"
  # install overlay only if it doesn't exist
  [ -f "$overlayFile" ] || updateActiveFile "$overlayFile"

  if [ $(grep -c "CAN+RS485 overlay" "$configFile") == 0 ]; then
    logMessage "activating CAN+RS485 DT overlay"
    echo "#### begin CAN+RS485 overlay" >> "$configFile"
    echo "dtparam=spi=on" >> "$configFile"
    echo "dtoverlay=mcp2515-can0,oscillator=16000000,interrupt=25,,spimaxfrequency=1000000" >> "$configFile"
    echo "dtoverlay=sc16is752-spi1,int_pin=24" >> "$configFile"
    echo "gpio=16=ip,pu" >> "$configFile"
    echo "#### end CAN+RS485 overlay" >> "$configFile"
    filesUpdated=true
  fi
fi

# uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
  restoreActiveFile "$gpioListFile"
  restoreActiveFile "$rulesFile"  
  restoreActiveFile "$overlayFile"

  # remove mods from configFile - do not use restore in case other mods were made manually
  if [ -f "$configFile" ]; then
    if [ $(grep -c "#### begin CAN+RS485 overlay" "$configFile") != 0 ]; then
      sed -i -e '/#### begin CAN+RS485 overlay/,/#### end CAN+RS485 overlay/d' "$configFile"
      filesUpdated=true
    fi
  fi
fi

if $filesUpdated ; then
  rebootNeeded=true
fi

# thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
endScript
